# Config file for Google Cloud Build, with App Engine deployment

# Visit Cloud Build's docs page for more details and extensibility:
# https://cloud.google.com/cloud-build/docs/<language>

# Since these steps are run in sequence, a failed test results in a fail
# in the overall build, and therefore no deployment (which is good)
steps:

# Run tests
- name: 'python:3.7-buster'
  entrypoint: 'make'
  args: ['test']

# Deploy to App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']

###
# Run functional tests, and roll back changes if anything is broken in prod
# But first, we'll need some helpers
###

# Download files from GS to shared volume:
#   - Service Account keyfile
#   - Live test script
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://kv-store/fredcast-248816_gcloudcli-support-user.json', '/cloudbuild-helpers/fredcast-248816_gcloudcli-support-user.json']
  volumes:
    - name: 'cloudbuild-helpers'
      path: '/cloudbuild-helpers'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://kv-store/live-tests.sh', '/cloudbuild-helpers/live-tests.sh']
  volumes:
    - name: 'cloudbuild-helpers'
      path: '/cloudbuild-helpers'

# Run live tests, and roll back AppEngine version if they fail
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args: ['/cloudbuild-helpers/live-tests.sh']
  volumes:
    - name: 'cloudbuild-helpers'
      path: '/cloudbuild-helpers'
